name: Main workflow
on: [workflow_dispatch]
jobs:
  production-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@v1.0.1
      with: 
        host: ${{secrets.PROD_IP}}
        username: ${{secrets.PROD_USER}}
        password: ${{secrets.PROD_PASSWORD}}
        script: | 
          echo "Connected to server!"; source ~/.nvm/nvm.sh; cd ./tgexpenses && git pull && scripts/startpm2
              
  
